[package]
name = "netdiscover"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Discover node network information (underlay/public IP, hostname)"
license = "Apache-2.0"
publish = false

[dependencies]
libc = "0.2"
stunclient = { version = "0.4.2", default-features = false }
ureq = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true
